apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-worker-autoscaler
  namespace: event-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-worker
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 15
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: notification_queue
      mode: QueueLength
      value: "20" # Scale out 1 additional worker for every 20 pending messages
      hostFromEnv: RABBITMQ_HOST
